blank_issues_enabled: false
contact_links:
  - name: Question or Support Request
    url: https://github.com/bamboechop/twitch-extension-stream-schedule/discussions
    about: Please ask questions in the Discussions section. 