import type { TwitchExtensionTheme, TwitchExtensionThemeConfiguration } from '../interfaces/twitch.interface';

export const themes: Record<Exclude<TwitchExtensionTheme, 'custom'>, TwitchExtensionThemeConfiguration> = {
  default: {
    backgroundColor: '#222222',
    dayBorderColor: '#62e9ff',
    fontColor: '#eeeeee',
    headerBackgroundColor: '#111111',
    headerFontColor: '#eeeeee',
    scheduleButtonBackgroundColor: '#62e9ff',
    scheduleButtonFontColor: '#111111',
    timeFontColor: '#cccccc',
    vacationBackgroundColor: '#62e9ff',
    vacationFontColor: '#62e9ff',
  },
  neonNights: {
    backgroundColor: '#120e29',
    dayBorderColor: '#ff00ff',
    fontColor: '#ffffff',
    headerBackgroundColor: '#0a0718',
    headerFontColor: '#ff00ff',
    scheduleButtonBackgroundColor: '#00ffff',
    scheduleButtonFontColor: '#0a0718',
    timeFontColor: '#00ffff',
    vacationBackgroundColor: '#ff00ff',
    vacationFontColor: '#ff00ff',
  },
  mintChocolate: {
    backgroundColor: '#2a2118',
    dayBorderColor: '#4ecca3',
    fontColor: '#eeeeee',
    headerBackgroundColor: '#1a150f',
    headerFontColor: '#4ecca3',
    scheduleButtonBackgroundColor: '#4ecca3',
    scheduleButtonFontColor: '#1a150f',
    timeFontColor: '#bdb9b5',
    vacationBackgroundColor: '#4ecca3',
    vacationFontColor: '#4ecca3',
  },
  sunsetVibes: {
    backgroundColor: '#2b2d42',
    dayBorderColor: '#f8961e',
    fontColor: '#edf2f4',
    headerBackgroundColor: '#1a1b2e',
    headerFontColor: '#f94144',
    scheduleButtonBackgroundColor: '#f8961e',
    scheduleButtonFontColor: '#1a1b2e',
    timeFontColor: '#90e0ef',
    vacationBackgroundColor: '#f8961e',
    vacationFontColor: '#f8961e',
  },
  royalPurple: {
    backgroundColor: '#2e1a47',
    dayBorderColor: '#ffd700',
    fontColor: '#f8f9fa',
    headerBackgroundColor: '#1d0b2e',
    headerFontColor: '#ffd700',
    scheduleButtonBackgroundColor: '#ffd700',
    scheduleButtonFontColor: '#1d0b2e',
    timeFontColor: '#d1b1ff',
    vacationBackgroundColor: '#ffd700',
    vacationFontColor: '#ffd700',
  },
  enchantedForest: {
    backgroundColor: '#1e352f',
    dayBorderColor: '#a1cca5',
    fontColor: '#f1f7ed',
    headerBackgroundColor: '#132a27',
    headerFontColor: '#a1cca5',
    scheduleButtonBackgroundColor: '#a1cca5',
    scheduleButtonFontColor: '#132a27',
    timeFontColor: '#beee9e',
    vacationBackgroundColor: '#a1cca5',
    vacationFontColor: '#a1cca5',
  },
  retroWave: {
    backgroundColor: '#2b213a',
    dayBorderColor: '#ff71ce',
    fontColor: '#fffbf7',
    headerBackgroundColor: '#241b31',
    headerFontColor: '#ff71ce',
    scheduleButtonBackgroundColor: '#ff71ce',
    scheduleButtonFontColor: '#241b31',
    timeFontColor: '#05ffa1',
    vacationBackgroundColor: '#ff71ce',
    vacationFontColor: '#ff71ce',
  },
  crystalClear: {
    backgroundColor: '#ffffff',
    dayBorderColor: '#3b82f6',
    fontColor: '#1f2937',
    headerBackgroundColor: '#f3f4f6',
    headerFontColor: '#1f2937',
    scheduleButtonBackgroundColor: '#3b82f6',
    scheduleButtonFontColor: '#ffffff',
    timeFontColor: '#6b7280',
    vacationBackgroundColor: '#0a55d3',
    vacationFontColor: '#0a55d3',
  },
  sakuraSpring: {
    backgroundColor: '#fdf2f8',
    dayBorderColor: '#ec4899',
    fontColor: '#831843',
    headerBackgroundColor: '#fbcfe8',
    headerFontColor: '#be185d',
    scheduleButtonBackgroundColor: '#ec4899',
    scheduleButtonFontColor: '#ffffff',
    timeFontColor: '#9d174d',
    vacationBackgroundColor: '#be185d',
    vacationFontColor: '#be185d',
  },
  oceanBreeze: {
    backgroundColor: '#f0fdfa',
    dayBorderColor: '#14b8a6',
    fontColor: '#134e4a',
    headerBackgroundColor: '#ccfbf1',
    headerFontColor: '#0f766e',
    scheduleButtonBackgroundColor: '#14b8a6',
    scheduleButtonFontColor: '#ffffff',
    timeFontColor: '#115e59',
    vacationBackgroundColor: '#0f766e',
    vacationFontColor: '#0f766e',
  },
  deepSpace: {
    backgroundColor: '#030712',
    dayBorderColor: '#8b5cf6',
    fontColor: '#e2e8f0',
    headerBackgroundColor: '#0f172a',
    headerFontColor: '#a78bfa',
    scheduleButtonBackgroundColor: '#8b5cf6',
    scheduleButtonFontColor: '#ffffff',
    timeFontColor: '#94a3b8',
    vacationBackgroundColor: '#7c3aed',
    vacationFontColor: '#7c3aed',
  },
  goldenHour: {
    backgroundColor: '#fffbeb',
    dayBorderColor: '#d97706',
    fontColor: '#78350f',
    headerBackgroundColor: '#fef3c7',
    headerFontColor: '#92400e',
    scheduleButtonBackgroundColor: '#d97706',
    scheduleButtonFontColor: '#ffffff',
    timeFontColor: '#b45309',
    vacationBackgroundColor: '#92400e',
    vacationFontColor: '#92400e',
  },
  lavenderFields: {
    backgroundColor: '#faf5ff',
    dayBorderColor: '#9333ea',
    fontColor: '#581c87',
    headerBackgroundColor: '#f3e8ff',
    headerFontColor: '#7e22ce',
    scheduleButtonBackgroundColor: '#9333ea',
    scheduleButtonFontColor: '#ffffff',
    timeFontColor: '#6b21a8',
    vacationBackgroundColor: '#7e22ce',
    vacationFontColor: '#7e22ce',
  },
};
