import type { TwitchExtensionTheme, TwitchExtensionThemeConfiguration } from '../interfaces/twitch.interface';

export const themes: Record<Exclude<TwitchExtensionTheme, 'custom'>, TwitchExtensionThemeConfiguration> = {
  default: {
    backgroundColor: '#222',
    dayBorderColor: '#62e9ff',
    fontColor: '#eee',
    headerBackgroundColor: '#111',
    headerFontColor: '#eee',
    scheduleButtonBackgroundColor: '#62e9ff',
    scheduleButtonFontColor: '#111',
    timeFontColor: '#ccc',
  },
  neonNights: {
    backgroundColor: '#120E29',
    dayBorderColor: '#FF00FF',
    fontColor: '#FFFFFF',
    headerBackgroundColor: '#0A0718',
    headerFontColor: '#FF00FF',
    scheduleButtonBackgroundColor: '#00FFFF',
    scheduleButtonFontColor: '#0A0718',
    timeFontColor: '#00FFFF',
  },
  mintChocolate: {
    backgroundColor: '#2A2118',
    dayBorderColor: '#4ECCA3',
    fontColor: '#EEEEEE',
    headerBackgroundColor: '#1A150F',
    headerFontColor: '#4ECCA3',
    scheduleButtonBackgroundColor: '#4ECCA3',
    scheduleButtonFontColor: '#1A150F',
    timeFontColor: '#BDB9B5',
  },
  sunsetVibes: {
    backgroundColor: '#2B2D42',
    dayBorderColor: '#F8961E',
    fontColor: '#EDF2F4',
    headerBackgroundColor: '#1A1B2E',
    headerFontColor: '#F94144',
    scheduleButtonBackgroundColor: '#F8961E',
    scheduleButtonFontColor: '#1A1B2E',
    timeFontColor: '#90E0EF',
  },
  royalPurple: {
    backgroundColor: '#2E1A47',
    dayBorderColor: '#FFD700',
    fontColor: '#F8F9FA',
    headerBackgroundColor: '#1D0B2E',
    headerFontColor: '#FFD700',
    scheduleButtonBackgroundColor: '#FFD700',
    scheduleButtonFontColor: '#1D0B2E',
    timeFontColor: '#D1B1FF',
  },
  enchantedForest: {
    backgroundColor: '#1E352F',
    dayBorderColor: '#A1CCA5',
    fontColor: '#F1F7ED',
    headerBackgroundColor: '#132A27',
    headerFontColor: '#A1CCA5',
    scheduleButtonBackgroundColor: '#A1CCA5',
    scheduleButtonFontColor: '#132A27',
    timeFontColor: '#BEEE9E',
  },
  retroWave: {
    backgroundColor: '#181829',
    dayBorderColor: '#F2545B',
    fontColor: '#E9EAF2',
    headerBackgroundColor: '#0C0C1D',
    headerFontColor: '#F2545B',
    scheduleButtonBackgroundColor: '#00D8EB',
    scheduleButtonFontColor: '#0C0C1D',
    timeFontColor: '#A4D4E0',
  },
  crystalClear: {
    backgroundColor: '#E8F1F5',
    dayBorderColor: '#2392D6',
    fontColor: '#1B365D',
    headerBackgroundColor: '#FFFFFF',
    headerFontColor: '#005C99',
    scheduleButtonBackgroundColor: '#2392D6',
    scheduleButtonFontColor: '#FFFFFF',
    timeFontColor: '#5A5A5A',
  },
};
